### ISSUE TITLE
Went Year 2 Flawless Last night, says year 1

### ISSUE THREAD

**Issue by taybizzal** [DestinyTrialsReport/DestinyTrialsReport#117]
Hi, my gamertag is DCALXP and, very delighted to say I went flawless for the first time last night, my report shows that I am year 1 flawless, instead of 1x Flawless (year 2). I play often and want to look cool. Please let me know how we can resolve this.

**Comment by v-fedorov** [comment]
We are behind on keeping current week data up to date, hoping to be caught up in a couple of hours
