### ISSUE TITLE
Opponents - Shows repeat of opponents twice

### ISSUE THREAD

**Issue by jawadmn** [DestinyTrialsReport/DestinyTrialsReport#119]
Seems to show repeats of opponents in a single listing, ie if my opponents for a match were, say, PersonA, PersonB, and PersonC, the list would show as...

PersonA
PersonB
PersonC
PersonA
PersonB
PersonC

All six items are technically part of a single set, so clicking one of them will "highlight" all six and show the same match on the right side. Every single set of opponents has an adjacent repeat like this.

Tested with Windows 10 Firefox & Chrome

**Comment by SteffanLong** [comment]
Can you provide a screenshot showing the issue?

**Comment by jawadmn** [comment]
I've just realized (especially after playing trials some more last night) that the repeats are from certain games from last weekend (from about pages 3 to 9 in my history at the moment right now). The game selected in the screenshot below was the last game I played last Trials, and the first instance of the repeats in my list of opponents.

![opponents x6 screenshot](https://cloud.githubusercontent.com/assets/8507867/12075210/e2baf0a6-b146-11e5-85cf-3e11f3db4bf3.png)

**Comment by jawadmn** [comment]
Also, no idea if this is a relevant issue...

Multiple repeat names (in odd ways):
![opponents x6 screenshot](https://cloud.githubusercontent.com/assets/8507867/12075232/b39cec6a-b147-11e5-82c9-adf8270c9489.png)

One of the same games in my list (only dragonrath repeats in this instance):
![opponents weird repeat screenshot](https://cloud.githubusercontent.com/assets/8507867/12075250/18ab1212-b148-11e5-8900-ca8d25a9d7c6.png)

**Comment by v-fedorov** [comment]
Hey @jawadmn thanks for the screenshots, turns out the issue is that our DB contains duplicated values when it really shouldn't.

Thanks for bringing this to our attention and we will fix it after trials ends this Tuesday.

**Comment by SteffanLong** [comment]
We've removed all duplicate entries from our database and added protections to ensure it can't happen again. Thank you for reporting this issue!
