### ISSUE TITLE
Reverse Proxy 

### ISSUE THREAD

**Issue by designgears** [DestinyTrialsReport/DestinyTrialsReport#120]
I'm trying to set this up using an nginx reverse proxy. I want to be able access it from example.com/trails. I got it to load the initial page, but everything ends up redirecting back to the home page. What would be the proper way to do this?

**Comment by SteffanLong** [comment]
You're not going to get it to work under a subfolder without changing some of our code. You'd be better off trying to get it to work under a subdomain. Here's an example configuration.

    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      
      server_name trials.example.com;
      root /var/www/trials.example.com;
      index index.html;
      
      location / {
        try_files $uri $uri/ /index.html =404;
      }
      
      location /Platform/ {
        proxy_pass https://www.bungie.net;
        proxy_set_header Host 'www.bungie.net';
        proxy_set_header X-API-Key '<YOUR API KEY HERE>';
      }
    }

**Comment by designgears** [comment]
Heh, that does seem like an easier approach. I have most things working under the subfolder now, just need to figure why the submit button just redirects back to the main page. I will create a branch and create a pull request when I get it fully working.

**Comment by SteffanLong** [comment]
If you don't have it under a subdomain, and your URLs look something like `/trials/ps/<username` it won't work because there is no match for that in the router. You'd have to change that yourself in the code. That's why I suggested the subdomain method, because then you wouldn't need to modify the routes.

What exactly are you trying to change and suggest we pull?

**Comment by SteffanLong** [comment]
I'm going to close this for now. Let us know if you need more help.
