### ISSUE TITLE
Round Robin API keys

### ISSUE THREAD

**Issue by EasyAsABC123** [DestinyTrialsReport/DestinyTrialsReport#121]
Allow for multiple api key with round robin calling

this resolves more API calls than bungie allows

**Comment by SteffanLong** [comment]
We're looking into it.

**Comment by EasyAsABC123** [comment]
@SteffanLong I went to run the code to add this feature but it appears you guys are running an older version of node, is updating to latest on the list?  if so I might do that first

**Comment by SteffanLong** [comment]
We're actually not using node as the web server anymore, that's just legacy code. We migrated to nginx.

Bungie actually throttles based on IP, not API key. So we need to set up a proxy to use multiple source IP addresses.

Using nginx to proxy off multiple source IPs is fairly trivial, but we're struggling with configuring the servers for those multiple IP addresses at the moment.

**Comment by EasyAsABC123** [comment]
@SteffanLong I highly recommend using Chef to configure the servers...you can do 20 servers for free on their instance and then just popup as many amazon ec2 servers as needed based on load...configured correctly...and create a deploy recipe in chef or puppet or any of the other config management tools

**Comment by SteffanLong** [comment]
Yup, that could work. We have an entire IPv6/64 block to use on our server, so we're trying to utilize that before we launch other servers.

**Comment by EasyAsABC123** [comment]
@SteffanLong understandable, I suppose it is all a thing of cost.  A single micro server on AWS is ~$60 a year.  so i can definitely understand no wanting to spin up a lot if donations aren't pouring in

**Comment by v-fedorov** [comment]
Im looking into the chef docs now to check it out.
Our main server is fine, we just either need to figure out how to utilize our IPv6 block or open up a cluster of proxy servers that we can route to.

**Comment by EasyAsABC123** [comment]
@v-fedorov let me know if there is anything i can assist with.  I have quite a bit of chef experience so i'm happy to assist where i can.

**Comment by v-fedorov** [comment]
Ok i made a simple reverse proxy Rack app. How easy is it to deploy to Chef?

**Comment by EasyAsABC123** [comment]
you are wanting to spin up multple aws boxes then just write a recipe that pulls via github/ftp/http/https/ssh and then do whatever steps you need to have it running :) i can help if i know more info

**Comment by EasyAsABC123** [comment]
@v-fedorov basically just think of it as if you were on the box running commands but you make a ruby script for it and then it will run it every 30 minutes or if a chef-client is called, or use https://docs.chef.io/push_jobs.html to make it update on all boxes

**Comment by v-fedorov** [comment]
@EasyAsABC123  decided to just make a quick fix using heroku.
we got our ipv6 stuff straightened out so we will finally be able to just do everything through nginx

**Comment by EasyAsABC123** [comment]
@v-fedorov awesome, and love heroku

**Comment by v-fedorov** [comment]
Thanks for the help thought :)

**Comment by EasyAsABC123** [comment]
@v-fedorov lol anytime, that does require a lot on my part ;)
