### ISSUE TITLE
Bungie API Key rate limits

### ISSUE THREAD

**Issue by jkissell** [DestinyTrialsReport/DestinyTrialsReport#123]
Gruntfile.js only uses one Bungie API Key.

As a result of high traffic during Trails weekends, Bungie starts refusing to return data to the public website, and therefore it becomes unusable.  

I suggest signing up for many Bungie API Keys and putting a different key on each server in the load balancer...  

But, if there aren't many servers this could be handled through code.  You could create an array of API KEYS and randomly use one when users of the website request information.  Thus increasing the number of API calls you can make against Bungie's data.

**Comment by jkissell** [comment]
Also, there is a API Key in the Gruntfile.js in github...  I hope you're not using that "live" as others are probably now using that as well, counting against your limit.

**Comment by SteffanLong** [comment]
Okay, so let me respond to a few of your points. :)

Grunt is only our testing environment. It only runs a basic web server and handles some basic tasks for us and is not used on live. Additionally, the API key we use and that is committed into GitHub is a public one.

Also, it's important to note that Bungie throttles based on IP, not API key. So using multiple API keys doesn't help us get around their limits. We have a solution in place, however, and we should never reach limits on live.
