### ISSUE TITLE
sudo node manifest.js issue

### ISSUE THREAD

**Issue by dpeet** [DestinyTrialsReport/DestinyTrialsReport#124]
Hey guys,

I pulled a copy to play with and host on my local ubuntu server.  Only had a few issues throughout the instructions, but I got stymied at the second to last command, sudo node manifest.js.  Gives the error

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open 'manifest/world_sql_content_e9d195835cd3f3587acc89b187b00714.content'
    at Error (native)
```
Is this something obvious I'm overlooking?  I ran grunt serve and it seemed to get stuck on the watch task.

Great work on the app, I use it every weekend!  Thanks.

**Comment by v-fedorov** [comment]
Hey dpeet, thanks for using it :)

That command isn't mandatory but to fix that error just create a folder named "manifest" in the root dir.

Also make sure you are pulling everything from the develop branch as well.
