### ISSUE TITLE
Rounding Error on mytrials report weapon stats.

### ISSUE THREAD

**Issue by ratchetnclank** [DestinyTrialsReport/DestinyTrialsReport#129]
Weapon stats page displays precision to more than 1 decimal place making it hard to read the rest of the page.

**Comment by SteffanLong** [comment]
Oh wow, thanks for this! We recently changed the way we work with numbers and must have missed this one. I'll get a fix up as soon as possible. Love your username! :)

**Comment by SteffanLong** [comment]
This is fixed in d4eaf37bd81fcb36c94b0b5aaf503678b6647d68. We will deploy the new build to live soon. Thanks for reporting this!
