### ISSUE TITLE
show this week and map stats

### ISSUE THREAD

**Issue by EasyAsABC123** [DestinyTrialsReport/DestinyTrialsReport#130]
On my laptop I see:
This week:
weapon stats
matches played
win lose
kills deaths
k/d

but it isn't on my desktop...
i've cleaned out my cache but nothing is there

![image](https://cloud.githubusercontent.com/assets/1851104/15102757/3571ff54-1571-11e6-9686-0a800807b945.png)

**Comment by SteffanLong** [comment]
Hi! Thanks for using DestinyTrialsReport!!

![image](https://cloud.githubusercontent.com/assets/5157291/16938858/dee8b496-4d30-11e6-8dc7-0ac4257cebc2.png)

We actually recently added the ability to customize the cards, so you see only what you want to see and nothing you don't! In the screenshot I posted, if you click "Language & Settings" you will be given a ton of options to customize what you see! Alternatively, you can toggle "Ignore Custom Card Settings" to override the toggles in settings, and just show everything!

Sorry for taking so long to reply to your issue! Thanks again!!
