### ISSUE TITLE
Formatting on MacOSX Firefox

### ISSUE THREAD

**Issue by animosity22** [DestinyTrialsReport/DestinyTrialsReport#132]
I didn't notice this on Chrome on my Mac, but on Firefox, it looks like this:

http://imgur.com/gupOxBA

I'm running latest Firefox 48.0 on OS X El Capitan 10.11.6

**Comment by SteffanLong** [comment]
We were having an issue with the icons earlier that we corrected. Can you confirm the problem was resolved?

**Comment by animosity22** [comment]
Yep. Looks good now. Appreciate the quick reply!

**Comment by SteffanLong** [comment]
Glad to hear it! Thanks for using DestinyTrialsReport! <3
