### ISSUE TITLE
Year 3 added to tooltips cause overflow

### ISSUE THREAD

**Issue by iBotPeaches** [DestinyTrialsReport/DestinyTrialsReport#134]
![year3](https://cloud.githubusercontent.com/assets/611784/19037877/aa2eb0c8-8946-11e6-81cc-ce63977a0d5f.JPG)

and

![year3-2](https://cloud.githubusercontent.com/assets/611784/19037881/ae1e076a-8946-11e6-8480-1e9e46e92a9b.JPG)

Might already be aware. 

Windows.
Chrome 52.

**Comment by v-fedorov** [comment]
Yeah I noticed it right after I deployed, thanks for making the PR though :)

**Comment by SteffanLong** [comment]
This has been fixed.
