### ISSUE TITLE
Xbox One player stats often do not load

### ISSUE THREAD

**Issue by stefanski23** [DestinyTrialsReport/DestinyTrialsReport#135]
My friend, GT: AceOfDiamonds often does not load on your site. For a while we thought it was temporary, but it has been happening for months. The players he is with will show up, but he will return no results. He really wants to donate to your site, but doesn't because his name never shows up. Hopefully you can find the issue.

**Comment by SteffanLong** [comment]
We've fixed this issue in our latest development build and we'll be pushing it to live as soon as we're ready. I see your friend had donated already. We appreciate your support! :D
