### ISSUE TITLE
Wont load anything past start page

### ISSUE THREAD

**Issue by FALLnG0D** [DestinyTrialsReport/DestinyTrialsReport#137]
I can't see anyone i type in

**Comment by SteffanLong** [comment]
Can you post a log from the console? (Usually CTRL-SHIFT-J) or do you get an error that would help us track down the issue for you?

**Comment by FALLnG0D** [comment]
It's from a note 5 but I'll try

**Comment by FALLnG0D** [comment]
Ok i couldn't find a way to get a log but I shared the link plus a couple
of screenshots I hope this helps thank you








https://towerghostfordestiny.com/share/?xbl/FALLEN%20G0D

On Dec 27, 2016 12:13 PM, "Michael Hickman" <diveoverdose@gmail.com> wrote:

It's from a note 5 but I'll try

**Comment by v-fedorov** [comment]
@FALLnG0D That link isnt working and i dont think you can attach images through email responses.

Can you reply directly through github or email the images directly to us at destinytrialsreport@gmail.com?

**Comment by v-fedorov** [comment]
@FALLnG0D can you try refreshing the site and trying search again?

**Comment by FALLnG0D** [comment]
It working just says no matches found but probably has something to do with
whatever WAS wrong thanks a lot. F.Y.I  2 weeks ago I emailed towerghost
about a problem and I haven't even got a reply you guys are doing a great
job. Have a GREAT NEW YEAR

**Comment by SteffanLong** [comment]
Glad we were able to track down the issue! We've been trying to find the cause of this for quite some time. Thanks for submitting the issue and let us know if you have any further issues! :D

**Comment by FALLnG0D** [comment]
No problem hope I was some tiny tiny bit of help.
