### ISSUE TITLE
Is there a way to create a class graphic using Destiny API?

### ISSUE THREAD

**Issue by queuebit** [DestinyTrialsReport/DestinyTrialsReport#139]
If I wanted to know how many female exo warlocks there were playing trials one weekend compared to male human hunters...

Similar to: 
https://fivethirtyeight.com/features/is-your-dd-character-rare/

**Comment by v-fedorov** [comment]
lol thats a pretty neat idea, its not sometime thats directly available unless you look at each profile individually and store the results.

Ill give this a shot when i get a chance, fyi for future reference you can post on https://github.com/Bungie-net/api/issues

**Comment by queuebit** [comment]
Thanks. I was more interested in what the trials community looked like each week; essentially a breakdown of `839,586 GUARDIANS` number is why I asked here.

Awesome work on everything, thanks for what you do. No need to implement unless **you** think it is cool. Feel free to close. ☮️

**Comment by v-fedorov** [comment]
Thanks! I actually do like it, im gathering this info now

**Comment by v-fedorov** [comment]
https://github.com/Bungie-net/api/issues/225

**Comment by queuebit** [comment]
https://www.reddit.com/r/DestinyTheGame/comments/763pl3/race_gender_class_breakdown_for_to9_week_4/
